# Generated by Django 6.0.5 on 2026-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_student_deleted_at_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
