# Generated by Django 6.0.5 on 2026-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_student_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='depends_on',
            field=models.CharField(blank=True, help_text='Label of the field this depends on', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='depends_on_value',
            field=models.CharField(blank=True, help_text='Value the parent field must have', max_length=100, null=True),
        ),
    ]
