# Generated by Django 6.0.5 on 2026-06-26 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formfield_depends_on_formfield_depends_on_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tierform',
            name='pass_percentage',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='tierform',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
