# Generated by Django 6.0.5 on 2026-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_student_user_submission_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
