# Generated by Django 6.0.5 on 2026-07-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_agent_school_student_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title or alt text', max_length=200, null=True)),
                ('media_file', models.FileField(upload_to='gallery/')),
                ('is_video', models.BooleanField(default=False, help_text='Check if this is a video file (mp4, webm)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which it appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
