# Generated by Django 6.0.5 on 2026-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Check if this is a video URL (mp4, webm)'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_file',
            field=models.URLField(help_text='Paste a direct image or video URL (e.g. from Google Drive, Imgur, WhatsApp CDN, etc.)', max_length=1000),
        ),
    ]
