# Generated by Django 6.0.5 on 2026-07-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_sitesettings_is_results_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='validation_message',
            field=models.CharField(blank=True, help_text='Error message if validation fails', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_pattern',
            field=models.CharField(blank=True, help_text='Regex pattern e.g. ^[0-9]{10}$', max_length=255, null=True),
        ),
    ]
