# Generated by Django 6.0.5 on 2026-07-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_formfield_validation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='force_uppercase',
            field=models.BooleanField(default=False, help_text='If checked, this field will automatically convert user input to UPPERCASE'),
        ),
    ]
